"""OpenAPI 3.0 and Protocol Buffers generators for a ServiceContract."""

from __future__ import annotations

import re
from typing import Any

from reposplit.agents.contract.typing_rules import json_type, proto_type
from reposplit.core.schemas import EndpointContract, ServiceContract
from reposplit.utils.naming import to_pascal

FLASK_PARAM = re.compile(r"<(?:(?P<conv>\w+):)?(?P<name>\w+)>")


def flask_path_to_openapi(path: str) -> tuple[str, list[tuple[str, str]]]:
    """'/api/v1/users/<int:user_id>' -> ('/api/v1/users/{user_id}', [('user_id', 'integer')])."""
    params: list[tuple[str, str]] = []

    def repl(m: re.Match[str]) -> str:
        conv = m.group("conv") or "string"
        jtype = {"int": "integer", "float": "number", "string": "string", "path": "string", "uuid": "string"}[conv]
        params.append((m.group("name"), jtype))
        return "{" + m.group("name") + "}"

    return FLASK_PARAM.sub(repl, path), params


def _body_schema(ep: EndpointContract) -> dict[str, Any] | None:
    keys = ep.body_keys or [p.name for p in ep.params if p.name not in ep.path_params]
    if not keys or ep.method == "GET":
        return None
    hints = {p.name: p.type_hint for p in ep.params}
    return {
        "type": "object",
        "properties": {k: {"type": json_type(k, hints.get(k))} for k in keys},
        "required": [k for k in keys if k not in {p.name for p in ep.params if not p.required}],
    }


def build_openapi(contract: ServiceContract, propagated_headers: list[str]) -> dict[str, Any]:
    paths: dict[str, Any] = {}
    schemas: dict[str, Any] = {}
    header_params = [
        {"name": h, "in": "header", "required": h == "traceparent", "schema": {"type": "string"}} for h in propagated_headers
    ]
    for ep in contract.endpoints:
        op: dict[str, Any] = {
            "operationId": ep.operation_id,
            "tags": [ep.exposure],
            "summary": f"{ep.exposure} endpoint ported from {ep.source_symbol}",
            "parameters": [
                *header_params,
                *[
                    {"name": p, "in": "path", "required": True, "schema": {"type": json_type(p, None)}}
                    for p in ep.path_params
                ],
            ],
            "responses": {
                "200": {"description": "OK", "content": {"application/json": {"schema": {"type": "object"}}}},
                "4XX": {"description": "Client error", "content": {"application/json": {"schema": {"$ref": "#/components/schemas/Error"}}}},
            },
        }
        body = _body_schema(ep)
        if body:
            name = f"{to_pascal(ep.operation_id)}Request"
            schemas[name] = body
            op["requestBody"] = {"required": True, "content": {"application/json": {"schema": {"$ref": f"#/components/schemas/{name}"}}}}
        if ep.method == "POST" and ep.exposure == "public":
            op["responses"]["201"] = {"description": "Created", "content": {"application/json": {"schema": {"type": "object"}}}}
        paths.setdefault(ep.path, {})[ep.method.lower()] = op
    schemas["Error"] = {"type": "object", "properties": {"error": {"type": "string"}}, "required": ["error"]}
    return {
        "openapi": "3.0.3",
        "info": {
            "title": to_pascal(contract.service),
            "version": "1.0.0",
            "description": f"Generated by RepoSplit 2.0 from the monolith boundary of {contract.service}.",
            "x-reposplit-port": contract.port,
        },
        "servers": [{"url": f"http://{contract.service}:{contract.port}"}],
        "paths": paths,
        "components": {"schemas": schemas},
    }


def build_proto(contract: ServiceContract) -> str:
    pkg = contract.service.removesuffix("_service")
    lines = [
        'syntax = "proto3";',
        f"package reposplit.{pkg}.v1;",
        "",
        "// Generated by RepoSplit 2.0 Contract Agent. Security context is carried in gRPC metadata:",
        "//   x-user-id, x-tenant-id, traceparent",
        "",
        f"service {to_pascal(contract.service)} {{",
    ]
    for ep in contract.endpoints:
        op = to_pascal(ep.operation_id)
        lines.append(f"  rpc {op} ({op}Request) returns ({op}Response);")
    lines.append("}")
    lines.append("")
    for ep in contract.endpoints:
        op = to_pascal(ep.operation_id)
        hints = {p.name: p.type_hint for p in ep.params}
        fields = list(dict.fromkeys(ep.path_params + [p.name for p in ep.params] + ep.body_keys))
        lines.append(f"message {op}Request {{")
        for i, f in enumerate(fields, start=1):
            lines.append(f"  {proto_type(f, hints.get(f))} {f} = {i};")
        lines.append("}")
        lines.append("")
        lines.append(f"message {op}Response {{")
        lines.append("  string payload_json = 1;  // TODO(team): replace with typed fields from the response model")
        lines.append("  int32 status_code = 2;")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)
